### ISSUE TITLE
splitter not work - skin classic

### ISSUE THREAD

**Issue by bajtpop** [JohnDoh/Roundcube-Plugin-Context-Menu#79]
Hi,
When I enable plugin, dot on splitter/separator is not displayed.
Skin: classic
RCM and Plugin is in latest version.

**Comment by JohnDoh** [comment]
it works ok for me with git-master. it sounds like there is going to be an error showing up in the JS console in your browser. is there?

**Comment by bajtpop** [comment]
Uncaught TypeError: a.indexOf is not a function(…)

When I enable plugin contextmenu_folder, the splitter is not displayed also in settings .

**Comment by JohnDoh** [comment]
where exactly does that error come from?

Also the contextmenu_folder plugin is a totally different project and nothing to do with me.

**Comment by bajtpop** [comment]
I will check it again by disabling plugins one by one.
I know that contextmenu_folder is different project .

**Comment by bajtek** [comment]
When I disabled contextmenu plugin, splitter is visible.

**Comment by JohnDoh** [comment]
ok... but like I said it works fine for me. What browser (and browser version) are you using? Earlier bajtpop mentioned a JS error but with no context. I need the error message yes but I need to know what it came from, which file, what line number. you have no other plugins enabled right? please say exact versions of roundcube and contextmenu plugin.

**Comment by bajtpop** [comment]
Sorry I wrote from my old  account. I use Firefox latest version: 50.0.2 . 
In firebug I see only TypeError: a.indexOf is not a function  program/js/jquery.min.js (row 36, column 19060)
If you want I can create you e-mail account and you will be able to check it in my rcm ?

Roundcube Webmail 1.3-git
contextmenu 	2.1.2

**Comment by JohnDoh** [comment]
ahh ok. this is about the versions. contextmenu 2.1.2 works fine with roundcube 1.2.3 but with git-master you get that error. please update contextmenu also to git-master. i'll release a new version of the plugin after roundcube 1.3-beta is released.

**Comment by bajtpop** [comment]
It's work. Thx.
